import './globals.css'
import Storedata from './context'
// import { ST } from 'next/dist/shared/lib/utils'
import bootstrap from '../node_modules/bootstrap/dist/css/bootstrap.min.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
         <Storedata>
              {children}
         </Storedata>
      </body>
    </html>
  )
}
